version: 2.1
jobs:
  build:
    # working_directory: ~/.
    docker:
      - image: circleci/node:10.16.3
      # - image: mongo:4.2.0
    steps:
      - checkout
      # - run:
      #     name: update-npm
      #     command: 'sudo npm install -g npm@5'
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  #  build:
  #    machine: # Specifies a machine image that uses
  #    # an Ubuntu version 14.04 image with Docker 17.06.1-ce
  #    # and docker-compose 1.14.0, follow CircleCI Discuss Announcements
  #    # for new image releases.
  #      image: circleci/classic:201708-01
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: unit-test
          command: npm run unit
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
           - build